export interface University {
    id: number;
    name: string;
    country: string;
    city: string;
    flag: string;
    tuitionUSD: number;
    matchScore: number;
    ranking: number;
    ieltsRequired: boolean;
    ieltsMin: number | null;
    programs: string[];
    scholarships: boolean;
    imageColor: string;
    crest: string;
}

export const universities: University[] = [
    {
        id: 1,
        name: "University of Manchester",
        country: "United Kingdom",
        city: "Manchester",
        flag: "🇬🇧",
        tuitionUSD: 28500,
        matchScore: 94,
        ranking: 32,
        ieltsRequired: true,
        ieltsMin: 6.5,
        programs: ["Data Science", "Computer Science", "Finance"],
        scholarships: true,
        imageColor: "bg-purple-100",
        crest: "🏛️",
    },
    {
        id: 2,
        name: "University of Toronto",
        country: "Canada",
        city: "Toronto",
        flag: "🇨🇦",
        tuitionUSD: 35000,
        matchScore: 91,
        ranking: 21,
        ieltsRequired: true,
        ieltsMin: 6.5,
        programs: ["Engineering", "Business", "Public Health"],
        scholarships: true,
        imageColor: "bg-blue-100",
        crest: "🍁",
    },
    {
        id: 3,
        name: "Technical University of Munich",
        country: "Germany",
        city: "Munich",
        flag: "🇩🇪",
        tuitionUSD: 3200,
        matchScore: 88,
        ranking: 37,
        ieltsRequired: false,
        ieltsMin: null,
        programs: ["Mechanical Engineering", "Informatics", "Physics"],
        scholarships: false,
        imageColor: "bg-slate-100",
        crest: "⚙️",
    },
    {
        id: 4,
        name: "University of Melbourne",
        country: "Australia",
        city: "Melbourne",
        flag: "🇦🇺",
        tuitionUSD: 32000,
        matchScore: 86,
        ranking: 14,
        ieltsRequired: true,
        ieltsMin: 7.0,
        programs: ["Medicine", "Law", "Environmental Science"],
        scholarships: true,
        imageColor: "bg-yellow-100",
        crest: "🦘",
    },
    {
        id: 5,
        name: "University of Cape Town",
        country: "South Africa",
        city: "Cape Town",
        flag: "🇿🇦",
        tuitionUSD: 8500,
        matchScore: 82,
        ranking: 160,
        ieltsRequired: false,
        ieltsMin: null,
        programs: ["Business", "Engineering", "Health Sciences"],
        scholarships: true,
        imageColor: "bg-green-100",
        crest: "🏔️",
    },
    {
        id: 6,
        name: "University of British Columbia",
        country: "Canada",
        city: "Vancouver",
        flag: "🇨🇦",
        tuitionUSD: 33000,
        matchScore: 89,
        ranking: 34,
        ieltsRequired: true,
        ieltsMin: 6.5,
        programs: ["Forestry", "Computer Science", "Economics"],
        scholarships: true,
        imageColor: "bg-teal-100",
        crest: "🌲",
    },
    {
        id: 7,
        name: "University of Leeds",
        country: "United Kingdom",
        city: "Leeds",
        flag: "🇬🇧",
        tuitionUSD: 24000,
        matchScore: 79,
        ranking: 75,
        ieltsRequired: true,
        ieltsMin: 6.0,
        programs: ["Media Studies", "Civil Engineering", "Education"],
        scholarships: false,
        imageColor: "bg-rose-100",
        crest: "🎓",
    },
    {
        id: 8,
        name: "RWTH Aachen University",
        country: "Germany",
        city: "Aachen",
        flag: "🇩🇪",
        tuitionUSD: 2800,
        matchScore: 85,
        ranking: 87,
        ieltsRequired: false,
        ieltsMin: null,
        programs: ["Electrical Engineering", "Automotive Engineering", "Chemistry"],
        scholarships: false,
        imageColor: "bg-cyan-100",
        crest: "🔧",
    },
    {
        id: 9,
        name: "University of Sydney",
        country: "Australia",
        city: "Sydney",
        flag: "🇦🇺",
        tuitionUSD: 34000,
        matchScore: 83,
        ranking: 19,
        ieltsRequired: true,
        ieltsMin: 7.0,
        programs: ["Architecture", "Pharmacy", "Data Analytics"],
        scholarships: true,
        imageColor: "bg-orange-100",
        crest: "🏗️",
    },
    {
        id: 10,
        name: "Arizona State University",
        country: "United States",
        city: "Tempe",
        flag: "🇺🇸",
        tuitionUSD: 30000,
        matchScore: 77,
        ranking: 105,
        ieltsRequired: true,
        ieltsMin: 6.0,
        programs: ["Sustainability", "Business", "Journalism"],
        scholarships: true,
        imageColor: "bg-amber-100",
        crest: "☀️",
    },
    {
        id: 11,
        name: "University of Warwick",
        country: "United Kingdom",
        city: "Coventry",
        flag: "🇬🇧",
        tuitionUSD: 27000,
        matchScore: 90,
        ranking: 64,
        ieltsRequired: true,
        ieltsMin: 6.5,
        programs: ["Mathematics", "Economics", "Computer Science"],
        scholarships: true,
        imageColor: "bg-indigo-100",
        crest: "📐",
    },
    {
        id: 12,
        name: "University of Waterloo",
        country: "Canada",
        city: "Waterloo",
        flag: "🇨🇦",
        tuitionUSD: 31000,
        matchScore: 87,
        ranking: 112,
        ieltsRequired: true,
        ieltsMin: 6.5,
        programs: ["Software Engineering", "Actuarial Science", "Nanotechnology"],
        scholarships: false,
        imageColor: "bg-violet-100",
        crest: "💧",
    },
];

export const countryOptions = [
    "All Countries",
    "United Kingdom",
    "Canada",
    "Germany",
    "Australia",
    "South Africa",
    "United States",
];

export const budgetOptions = [
    { label: "Any Budget", min: 0, max: Infinity },
    { label: "Under $10,000", min: 0, max: 10000 },
    { label: "$10,000 – $25,000", min: 10000, max: 25000 },
    { label: "$25,000 – $35,000", min: 25000, max: 35000 },
    { label: "Over $35,000", min: 35000, max: Infinity },
];
