import {
    CameraMicrophone01Icon,
    GraduationScrollIcon,
    AiSearchIcon,
    DocumentAttachmentIcon,
    Wallet01Icon,
    Shield01Icon,
    CheckListIcon,
    Luggage01Icon,
} from "hugeicons-react";

const services = [
    {
        icon: CameraMicrophone01Icon,
        title: "AI Visa Interview Prep",
        description:
            "Realistic mock interviews with AI feedback, confidence scoring, and targeted improvement tips.",
        badge: "AI Powered",
    },
    {
        icon: GraduationScrollIcon,
        title: "University Matching",
        description:
            "Universities matched to your profile, budget, and career goals in minutes.",
        badge: "AI Powered",
    },
    {
        icon: CheckListIcon,
        title: "Transcript Evaluation",
        description:
            "AI-powered GPA conversion, credential review, and eligibility checks from your transcript.",
        badge: "AI Powered",
    },
    {
        icon: AiSearchIcon,
        title: "Scholarship Finder",
        description:
            "Surface scholarships by country, field, and affordability. Never miss funding again.",
        badge: "AI Powered",
    },
    {
        icon: DocumentAttachmentIcon,
        title: "SOP & CV Builder",
        description:
            "Tailored Statements of Purpose and CVs, generated by AI, ready to submit.",
        badge: "AI Powered",
    },
    {
        icon: Wallet01Icon,
        title: "Financial Guidance",
        description:
            "Budget tools, currency conversion, and education loan matching, all in one place.",
    },
    {
        icon: Shield01Icon,
        title: "Visa Success System",
        description:
            "Smart checklists and probability scoring to maximize your visa approval chances.",
    },
    {
        icon: Luggage01Icon,
        title: "Pre-departure Guidance",
        description:
            "Complete checklists, travel tips, and essential documentation to prepare for your departure.",
    },
];

export function Services() {
    return (
        <section id="services" className="py-24 sm:py-32 relative overflow-hidden bg-slate-50/50">
            {/* Soft background accents */}
            <div className="absolute top-0 right-0 -translate-y-12 translate-x-1/3 w-[800px] h-[400px] bg-[#1f639b]/5 blur-[100px] rounded-full pointer-events-none" />
            <div className="absolute bottom-0 left-0 translate-y-1/3 -translate-x-1/3 w-[600px] h-[600px] bg-[#2d8a4e]/5 blur-[120px] rounded-full pointer-events-none" />

            <div className="mx-auto max-w-[90rem] px-4 sm:px-6 lg:px-8 relative z-10">
                {/* Section header */}
                <div className="mx-auto max-w-3xl text-center">
                    <span className="inline-flex items-center justify-center rounded-full border border-[#1f639b]/20 bg-[#1f639b]/5 px-4 py-1.5 text-sm font-medium text-[#1f639b] mb-6">
                        Our Services
                    </span>
                    <h2 className="text-4xl font-extrabold tracking-tight text-slate-900 sm:text-5xl lg:text-[3.5rem] leading-[1.1]">
                        Everything you need to study abroad
                    </h2>
                    <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-slate-500">
                        From your first profile to boarding your flight, every step
                        covered with expert tools and AI guidance.
                    </p>
                </div>

                {/* Services grid */}
                <div className="mx-auto mt-16 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                    {services.map((service) => (
                        <div
                            key={service.title}
                            className="group relative flex flex-col rounded-[1rem] bg-white p-5 shadow-sm ring-1 ring-slate-200/50 transition-all duration-300 hover:-translate-y-1.5 hover:shadow-xl hover:shadow-[#1f639b]/10 hover:ring-[#1f639b]/20 overflow-hidden"
                        >
                            {/* Card gradient effect on hover */}
                            <div className="absolute inset-0 bg-gradient-to-br from-[#1f639b]/[0.02] to-transparent opacity-0 transition-opacity duration-300 group-hover:opacity-100" />
                            
                            {service.badge && (
                                <div className="absolute top-4 right-4 inline-flex items-center rounded-full bg-[#2d8a4e]/10 px-2 py-0.5 text-[9px] font-bold uppercase tracking-wide text-[#2d8a4e] ring-1 ring-inset ring-[#2d8a4e]/20">
                                    {service.badge}
                                </div>
                            )}
                            
                            <div
                                className="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-[#1f639b]/5 text-[#1f639b] transition-all duration-300 group-hover:bg-[#1f639b] group-hover:text-white group-hover:scale-110 group-hover:rotate-3 group-hover:shadow-md group-hover:shadow-[#1f639b]/20"
                            >
                                <service.icon size={20} strokeWidth={1.5} className="transition-transform duration-300" />
                            </div>
                            
                            <div className="relative z-10 flex-1">
                                <h3 className="text-[15px] font-bold text-slate-900 group-hover:text-[#1f639b] transition-colors duration-300">
                                    {service.title}
                                </h3>
                                <p className="mt-2 text-[13px] leading-relaxed text-slate-500">
                                    {service.description}
                                </p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
}
