import {
    CameraMicrophone01Icon,
    GraduationScrollIcon,
    AiSearchIcon,
    DocumentAttachmentIcon,
    Wallet01Icon,
    Shield01Icon,
    CheckListIcon,
    Luggage01Icon,
} from "hugeicons-react";

const services = [
    {
        icon: CameraMicrophone01Icon,
        title: "AI Visa Interview Prep",
        description:
            "Realistic mock interviews with AI feedback, confidence scoring, and targeted improvement tips.",
    },
    {
        icon: GraduationScrollIcon,
        title: "University Matching",
        description:
            "Universities matched to your profile, budget, and career goals in minutes.",
    },
    {
        icon: CheckListIcon,
        title: "Transcript Evaluation",
        description:
            "AI-powered GPA conversion, credential review, and eligibility checks from your transcript.",
    },
    {
        icon: AiSearchIcon,
        title: "Scholarship Finder",
        description:
            "Surface scholarships by country, field, and affordability. Never miss funding again.",
    },
    {
        icon: DocumentAttachmentIcon,
        title: "SOP & CV Builder",
        description:
            "Tailored Statements of Purpose and CVs, generated by AI, ready to submit.",
    },
    {
        icon: Wallet01Icon,
        title: "Financial Guidance",
        description:
            "Budget tools, currency conversion, and education loan matching, all in one place.",
    },
    {
        icon: Shield01Icon,
        title: "Visa Success System",
        description:
            "Smart checklists and probability scoring to maximize your visa approval chances.",
    },
    {
        icon: Luggage01Icon,
        title: "Pre-departure Guidance",
        description:
            "Complete checklists, travel tips, and essential documentation to prepare for your departure.",
    },
];

export function Services() {
    return (
        <section id="services" className="py-16 sm:py-24">
            <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                {/* Section header */}
                <div className="mx-auto max-w-2xl text-center">
                    <span className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">
                        Our Services
                    </span>
                    <h2 className="mt-4 text-3xl font-bold tracking-tight text-text-primary sm:text-4xl lg:text-[2.75rem]">
                        Everything you need to study abroad
                    </h2>
                    <p className="mx-auto mt-5 max-w-lg text-base leading-relaxed text-slate-400 sm:text-[1.05rem]">
                        From your first profile to boarding your flight, every step
                        covered with expert tools and AI guidance.
                    </p>
                </div>

                {/* Services grid */}
                <div className="mx-auto mt-20 grid max-w-6xl gap-x-8 gap-y-14 sm:grid-cols-2 lg:grid-cols-4">
                    {services.map((service) => (
                        <div
                            key={service.title}
                            className="group mx-auto max-w-xs text-center"
                        >
                            <div
                                className="mx-auto mb-6 flex h-[4.25rem] w-[4.25rem] items-center justify-center rounded-full bg-slate-100 text-slate-600 transition-transform duration-300 ease-[cubic-bezier(0.22,1,0.36,1)] group-hover:scale-110"
                            >
                                <service.icon size={26} />
                            </div>
                            <h3 className="text-lg font-semibold text-text-primary">
                                {service.title}
                            </h3>
                            <p className="mt-2.5 text-[0.925rem] leading-relaxed text-slate-400">
                                {service.description}
                            </p>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
}
